name: Deploy to EC2 via Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/Phishing-url-detection-api
          git pull origin main

      - name: Rebuild and restart container
        run: |
          cd ~/phishing-url-detection-api
          docker-compose down
          docker-compose up -d --build
